### ISSUE TITLE
Feature Request: Finer control of buzzer duration

### ISSUE THREAD

**Issue by csharpfritz** [Jewelbots/arduino-library#19]
From the forums, there is a request for being able to call the buzzer with a specified buzz duration.

From this thread:  http://alpha.jewelbots.com/t/finer-control-of-buzzer/254

**Comment by csharpfritz** [comment]
I propose adding a Buzzer::buzz(duration) method with an error check to keep the buzzer from running longer than 2 seconds.

Why 2 seconds?  Why not?  Lets not burn out the motor, but I have no idea if the buzzer will run for 2 seconds or what the limit of the buzzer is

**Comment by SaraJo** [comment]
I don't think there is a limit. Thanks for adding it to Github, as I commented I thought "I need to think of somewhere to store things like this". We are out for the week this week but will discuss it next week when we are back. Working to prioritize new features.

**Comment by davison-sm** [comment]
I agree it is a good idea.  The mode needed for the haptics driver chip to operate as suggested is not implemented in our current code.

As a temporary measure, I just added additional buzz functions to give everyone 6 different lengths of buzzes (125 ms to 1.5 s).  And will be looking into adding an additional function with variable duration in the near future.  As noted above, there will be some limits to protect the hardware, but need to double check on those before I say anything specific.

Thanks again for the suggestion, am excited to roll out that feature in the near future.

**Comment by davison-sm** [comment]
Now available custom buzzer control!

The newest version of the Jewelbot Arduino Library (v1.0.2) how has a custom buzzer function.

In addition to customizing the length of time of the buzz, you can also specify the amplitude (or strength) of the vibration.  Check out the forum API page here ( http://community.jewelbots.com/t/working-with-the-jewelbot-buzzer/156 ) or our Github Wiki ( https://github.com/Jewelbots/arduino-library/wiki/Buzzer ) for details. 

We also added versioning to the Arduino Library in this release.  Your Arduino IDE should offer the option to update to v1.0.2 when you go into "Boards Manager."

Happy Buzzing!
