### ISSUE TITLE
Example from the main readme fails to compile

### ISSUE THREAD

**Issue by zosnap** [Jewelbots/arduino-library#20]
The "hello world" sketch on the main readme fails to compile with the error "'class LED' has no member named 'on'". The example at https://github.com/Jewelbots/arduino-library/blob/master/jewelbots_nRF51822_board_v100/Examples/JWB_blank/JWB_blank.ino does compile, so either that should get moved up to the main page, or the existing example should be updated to reference `turn_on_all` or some other method that exists.

**Comment by glennblock** [comment]
Thanks Zoe! If you'd like you can send us a PR, otherwise someone will fix.

**Comment by davison-sm** [comment]
Thanks, merged the pull request to update the example.
