### ISSUE TITLE
LED function parameters are misleadingly named

### ISSUE THREAD

**Issue by alexdean** [Jewelbots/arduino-library#22]
in `LED.h`, the timing parameters for `flash_single` and `flash_all` are incorrectly named `microseconds`. They are actually expecting milliseconds.

compare [LED.h](https://github.com/Jewelbots/arduino-library/blob/9dd9ac60de0532b4baa48db3428729f992be8a76/jewelbots_nRF51822_board_v100/cores/JWB_nRF51822/LED.h#L23-L24) to [LED.cpp](https://github.com/Jewelbots/arduino-library/blob/9dd9ac60de0532b4baa48db3428729f992be8a76/jewelbots_nRF51822_board_v100/cores/JWB_nRF51822/LED.cpp#L66-L78).

it's a minor issue, but was a little surprising when my daughter and i stumbled across it.

**Comment by davison-sm** [comment]
Thanks for finding that and letting us know.  It has been corrected in commit fe2691a
