### ISSUE TITLE
error where JB locks up

### ISSUE THREAD

**Issue by oldanderw** [Jewelbots/arduino-library#26]
MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Sierra v10.12.5
 
1) open a sketch, does not matter if its new file or user made sketch
2) plug in your JB and try to upload your code WITHOUT putting the JB into the upload mode
 there will be an error
3) click the verify button to verify your code(I had no errors what so ever when checking my sketch)
4) put the JB into uploading mode
5) try to upload your sketch
 it gives me the same error of step number 2. The JB does not exit out of uploading mode and no matter what I seem to do either on the JB or on the Arduino, The JB does not seem to react either to the sketch that is on it or the new sketch I tried uploading, in fact it seems to do nothing.

The only solution that seems to work is the 2 min timeout of the uploading mode(I have not been able to test the reset button because I don’t have anything small enough around me that will fit)

Please try this yourself and feel free to try to change it up a little bit to see if there are one than one way of doing this and if this is only happens on mac or it happens on macs, windows and linux

**Comment by SaraJo** [comment]
Hmmm, I followed these steps and cannot replicate. Can you do once more and confirm? What version of the arduino IDE do you have?

**Comment by oldanderw** [comment]
I have:
- Arduino v1.8.5
- Jewelbots Firmware v1.1.6
- Jewelbots Friendship v1.1.8
- Jewelbots Arduino v1.1.3

ok I just found out I left out some steps that led to the bug.1) so I **plugin** the JB into my computer already having my sketch open 2) then I **Verify** my code(I do this everytime I open my sketch even if I made it myself just so I know 100% that there are no errors in my code) 3) and try to **upload** the sketch **without** putting the JB into **upload mode** then 4) putting the JB into **upload mode** and then 5) **Verify** the sketch once more to kind of clear the console and finally **upload** the sketch to the JB with in the 2min upload period.

> it gives me the same error of step number 2. The JB does not exit out of uploading mode and no matter what I seem to do either on the JB or on the Arduino, The JB does not seem to react either to the sketch that is on it or the new sketch I tried uploading, in fact it seems to do nothing. The only solution that seems to work is the 2 min timeout of the uploading mode(I have not been able to test the reset button because I don’t have anything small enough around me that will fit)

**Comment by oldanderw** [comment]
I think a good solution would be after clicking the upload button for something to check if the JB is in upload mode before it even attempts to upload the sketch to the JB but I don't know if that would be possible or not

**Comment by SaraJo** [comment]
Haven't tried to replicate this yet. Going to shortly. Thanks.

**Comment by SaraJo** [comment]
Hmmmm, I cannot replicate this on my machine/firmware. Going to leave this open for a bit in case someone can.

**Comment by SaraJo** [comment]
I think this hasn't popped up again, but we will keep an eye out.
