### ISSUE TITLE
Developer Guidance?

### ISSUE THREAD

**Issue by rwaldron** [Jewelbots/arduino-library#5]
Is there any document that provides developer guidance for this library? Specifically, how do I use the repo master (or feature branch) as the source in Arduino IDE? When working with other Arduino libraries, that are board specific, the board definitions that are installed via `Tools -> Board -> Boards Manager` are decoupled from the libraries installed via `Sketch -> Include Library -> Manage Libraries`. That enables placing a development repo in the `~/Documents/Arduino/libraries/` directory

**Comment by SaraJo** [comment]
This is a great suggestion and something we can get together. I'd love to see how other people are doing it, @rwaldron, do you have an example of people that are doing it well?

**Comment by SaraJo** [comment]
So, I looked into this a bit and I believe that what @noopkat makes it much easier and is the best way to do this. There is a link on the Wiki. I don't believe that you can treat a board like a normal library by having the folders where the libraries are. Her solution is super elegant.

**Comment by glennblock** [comment]
@rwaldron I posted a path for doing this via symlinks. The main difference between my approach and @noopkat's awesome CLI is you can use the Arduino IDE. It is linked to in the wiki.

**Comment by glennblock** [comment]
http://alpha.jewelbots.com/t/contributing-to-arduino-library/168
