### ISSUE TITLE
BLE services / characteristics

### ISSUE THREAD

**Issue by noopkat** [Jewelbots/arduino-library#7]
I think I tried to run before I could walk (I got excited hehe, my fault) - but I connected via BLE to the Jewelbot bracelet (not the dev board) and I didn't get any services or characteristics back (but did get a list of service UUIDs `['180d', '1814']`). Again I'm jumping ahead, but are these set up manually via the sketch file uploaded to the device? If so, I can dig around and have a go at that.

In the meantime, I'll try to be more helpful by uploading the example sketch on both the dev board and the bracelet :grin:

**Comment by SaraJo** [comment]
The list of UUIDs are the bots that device is friends with. That's how they detect each other using the default firmware. Basically, that little guy is advertising that it is a JBot in its own way.

**Comment by gortok** [comment]
Those two uuids are the list of BLE services the Jewelbot exposes when it advertises. It exposes the Device Information Service (180d), and the running and cadence service (1814): https://www.bluetooth.com/specifications/gatt/viewer?attributeXmlFile=org.bluetooth.service.running_speed_and_cadence.xml

If you have connected to and bonded with the bot, you'll also see the custom services, The Jewelbots Control service, which exposes the friendslist and DFU; as well as the Annotated Alert Service, which is currently how Jewelbots send messages. I think we also have the Light Button Service exposed, which would expose the lights and buttons to custom inputs (the idea was to use that for the basis of control through the app).

The arduino library only exposes the basic hardware checkout code right now, and doesn't expose any of the custom firmware / radio stuff we have on the Jewelbots. For that to happen, a few things need to occur:

- custom timers replace for loops in sketches
- modifying the FSM to allow for user code to be run.

**Comment by SaraJo** [comment]
Thanks, George, for the detailed follow up. Super helpful. Flagging the "well, actually". None of that around these parts.

**Comment by gortok** [comment]
The exposing of Service 1814 while advertising is a bug and should be removed. We don't have the Running and Cadence Service on the bot. That was something that came in as an artifact of me using the template that exposed that.

**Comment by noopkat** [comment]
thanks for the info, Sara and George! So I was definitely connected to the Jewelbot (I wasn't just reading the advertisements), but it seems I need to 'bond' with it also, from what you're saying? Then the services will be available?  Does bonding mean becoming a friend on the list?

Thanks!

**Comment by gortok** [comment]
I don't quite remember the process for seeing the friends list and other things without the app;  I do know that I coded it to only show through if bonded. Once the arduino library code uses the base application firmware you'd be able to code things to deal with your friend list.  Since you have a commercial Jewelbot you'll be able to see it once you bond. LightBlue doesn't support bonding, but the Dev board does if you happen to have a segger + Nordic's flash.

The problem you'll run into is if you were to upload the arduino library firmware to your bot, you will lose the commercial application firmware on there; since the arduino library doesn't contain the application firmware. :-/

**Comment by noopkat** [comment]
cool. For context, I was using NodeJS and a native bluetooth module to do all of this, so was trying to see if I could 'friend' the bracelet by sending the correct handshakes etc etc. Was being cheeky!

**Comment by gortok** [comment]
It is "Just works" bonding, so as long as the Jewelbot is in bonding mode (plugged in + button press), then you'll be able to see those services.

**Comment by noopkat** [comment]
👌  🙆  yusss thank you I'm going to have a play
