### ISSUE TITLE
Board package URL in README.md is a 404

### ISSUE THREAD

**Issue by terescode** [Jewelbots/arduino-library#9]
Was interested in forking the repo and playing around.  On setup, noticed the URL for the staging pkg JSON is a 404.

https://jewelbots.github.io/arduino-library/package_jwb_staging_index.json

also tried a few guesses like

https://jewelbots.github.io/arduino-library/package_jewelbots_staging_index.json
https://jewelbots.github.io/arduino-library/package_jewelbots_staging.json

all 404's

**Comment by SaraJo** [comment]
@terescode where are you seeing that URL? That's actually the staging repo that we are using to stage and test changes before sending them to this repository. It shouldn't be public (it's https://jewelbots.github.io/arduino-library-staging/package_jwb_staging_index.json). 

We are working on a way to help everyone with a staging repo. Open to suggestions on how to make it easy for folks to contribute.

**Comment by terescode** [comment]
@SaraJo first you shouldn't be working on a holiday weekend!  And I guess I shouldn't be hacking...

https://github.com/Jewelbots/arduino-library/blob/master/README.md

It's right in your README markdown for this repo.

Maybe you could have a staging branch of the repo(s)?  I would recommend the standard fork/PR model using multiple branches.

**Comment by SaraJo** [comment]
Fixed the README. 

The staging branch makes sense, but then there would also need to be a separate .json file for staging. That would be fine too, I suppose. 

This is on my list of things to resolve this week.

**Comment by terescode** [comment]
Cool.  Got the staging board installed. Unrelated to this issue and slightly noob question so I apologize, will uploading the test sketch wipe out the OOB functionality of the device?  My girls might be upset if I nuke their devices on day 1. :-)

**Comment by SaraJo** [comment]
Yes, but it's easy to revert back. Instructions are under "update my firmware" on the [http//jewelbots.com/go](url) page.

**Comment by terescode** [comment]
Well... easy if you understand the tech.  And I guess if you are toying with the device anyway, its implied you understand the tech.  You may want to make that really clear somewhere in the docs though.  Thanks for your responsiveness.

**Comment by SaraJo** [comment]
That's helpful, @terescode. Thanks. We're also working on a way to update it more easily, as I agree it takes some effort/understanding.

**Comment by terescode** [comment]
Hey @SaraJo do you have any contributing directions yet?  Also can you point me in the direction of your Makefile or grunt/gulp file or other build system?

**Comment by SaraJo** [comment]
No, that is my big task over the next few days. Would love to see people that are doing it well. We have a jenky system setup for us internally, but it's not ideal for people externally (or us, tbh). Stay tuned. 

For the Makefile, do you mean for local dev as well? We have found the bet way to be reinstalling the board to check. Though, a Makefile would be great for syntax errors.

**Comment by noopkat** [comment]
@terescode @SaraJo I'm interested in helping build this. I started playing with a json config file and watch task in javascript, but can also look at creating a Makefile version also 😄

**Comment by SaraJo** [comment]
That's awesome, keep us posted and lmk if we can be helpful.

**Comment by SaraJo** [comment]
While opening up good points this specific issue is complete.
